In [1]:
import pandas as pd
import numpy as np
import os
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
messages = pd.read_csv('./data/spam.csv', encoding='latin1')
messages.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [8]:
messages = messages[['v1', 'v2']]
messages.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [9]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\AGLI
[nltk_data]     IT\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()

In [32]:
from tqdm import tqdm
corpus = []
for i in tqdm(range(0, len(messages))):
    review = re.sub('[^a-zA-Z]', ' ', messages['v2'][i]) #Regex
    review = review.lower() #Lowercase
    review = review.split() #List
    review = [stemmer.stem(word) for word in review if word not in set(stopwords.words('english'))] #Stemming and Stopwords
    review = ' '.join(review) #Again to sentence
    corpus.append(review)

100%|██████████| 5572/5572 [00:33<00:00, 166.81it/s]


In [35]:
corpus[:5]

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though']

In [53]:
# Creating BOW
from sklearn.feature_extraction.text import CountVectorizer
bow = CountVectorizer(max_features=2500)

In [54]:
X = bow.fit_transform(corpus).toarray()
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [57]:
X.shape, len(bow.vocabulary_)

((5572, 2500), 2500)

In [58]:
# For Binary Bag of Words - bow = Countvectorizer(max_features=2500, binary=True)

# NGrams

In [64]:
from sklearn.feature_extraction.text import CountVectorizer

ng_bow = CountVectorizer(max_features=3000, binary=True,ngram_range=(1, 2)) # Unigram and Bigram
ng_bow

CountVectorizer(binary=True, max_features=3000, ngram_range=(1, 2))

In [65]:
X = ng_bow.fit_transform(corpus).toarray()
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [66]:
len(ng_bow.vocabulary_)

3000

In [68]:
ng_bow.vocabulary_

{'go': 947,
 'point': 1919,
 'crazi': 525,
 'avail': 142,
 'bugi': 269,
 'great': 1016,
 'world': 2918,
 'la': 1306,
 'cine': 400,
 'got': 998,
 'wat': 2808,
 'ok': 1761,
 'lar': 1319,
 'joke': 1262,
 'wif': 2871,
 'oni': 1784,
 'ok lar': 1764,
 'free': 848,
 'entri': 723,
 'wkli': 2901,
 'comp': 463,
 'win': 2876,
 'cup': 544,
 'final': 805,
 'tkt': 2563,
 'st': 2358,
 'may': 1518,
 'text': 2496,
 'receiv': 2039,
 'question': 1993,
 'std': 2374,
 'txt': 2640,
 'rate': 2009,
 'appli': 99,
 'free entri': 855,
 'entri wkli': 725,
 'wkli comp': 2902,
 'cup final': 545,
 'std txt': 2375,
 'txt rate': 2649,
 'rate appli': 2011,
 'dun': 678,
 'say': 2147,
 'earli': 687,
 'alreadi': 63,
 'nah': 1657,
 'think': 2525,
 'goe': 973,
 'usf': 2734,
 'live': 1397,
 'around': 112,
 'though': 2536,
 'freemsg': 868,
 'hey': 1100,
 'darl': 571,
 'week': 2834,
 'word': 2911,
 'back': 160,
 'like': 1380,
 'fun': 892,
 'still': 2377,
 'tb': 2468,
 'xxx': 2958,
 'send': 2185,
 'rcv': 2017,
 'like fun': 1382

In [69]:
ng_bow = CountVectorizer(max_features=300, binary=True, ngram_range=(2, 3)) # Bigrams and Trigrams
ng_bow

CountVectorizer(binary=True, max_features=300, ngram_range=(2, 3))

In [71]:
X = ng_bow.fit_transform(corpus).toarray()
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [75]:
ng_bow.vocabulary_, len(ng_bow.vocabulary_)

({'free entri': 84,
  'rate appli': 206,
  'claim call': 42,
  'call claim': 13,
  'claim code': 43,
  'updat latest': 270,
  'free call': 83,
  'call mobil': 24,
  'chanc win': 41,
  'txt word': 265,
  'let know': 141,
  'feel like': 79,
  'repli ye': 213,
  'go home': 99,
  'call repli': 30,
  'mobil free': 163,
  'pleas call': 193,
  'lt gt': 154,
  'miss call': 160,
  'want go': 288,
  'first time': 82,
  'like lt': 142,
  'like lt gt': 143,
  'sm ac': 230,
  'sorri call': 231,
  'call later': 22,
  'sorri call later': 232,
  'award bonu': 8,
  'prize call': 201,
  'ur award': 271,
  'call free': 16,
  'that cool': 252,
  'call custom': 14,
  'custom servic': 60,
  'servic repres': 225,
  'guarante cash': 114,
  'cash prize': 40,
  'pleas call custom': 194,
  'call custom servic': 15,
  'custom servic repres': 61,
  'guarante cash prize': 115,
  'tri contact': 259,
  'draw show': 67,
  'show prize': 226,
  'prize guarante': 204,
  'guarante call': 112,
  'valid hr': 283,
  'draw sh